config/routes.rb
Rails.application.routes.draw do
  resources :departments do
    resources :items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    # render partial: "form"
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    # render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_sub
  before_action :set_item, except: [:index, :new, :create]
  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
  end

  def create
    @item = @department.item.new(item_params)
    if @item.save
      redirect_to department_item
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_sub
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/departments/_navbar.html.erb
<%= link_to 'Department', departments_path %>
<%= link_to 'Create New Department', new_department_path %>

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<%= render "form" %>

app/views/departments/index.html.erb
<h1>Store Departments</h1>
<% @departments.each do |department| %>
  <%= department.name %>
  <%= link_to 'Show Items', department_path(department.id) %>
  <%= link_to 'Edit', edit_department_path(department.id) %>
  <%= link_to 'Delete', department_path(department.id), method: :delete %>
  <br />
  <% end %>

app/views/departments/new.html.erb
<h1>Create New Department</h1>
<%= render "form" %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>

<%= link_to "Items click here", department_item_path(@department) %>
<%= link_to "Add items", new_department_item_path(@department) %>

app/views/items/_form.html.erb
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit %>
  <% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1> Add New Item </h1>
<%= render 'form' %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'departments/navbar' %>
    <%= yield %>
  </body>
</html>